# Generated by Django 4.2.7 on 2023-12-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1994-05-01'),
            preserve_default=False,
        ),
    ]
