# Generated by Django 4.2.7 on 2023-11-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pics',
            old_name='descrip',
            new_name='descr',
        ),
    ]
